[package]
description = "Parser for the Kerberos protocol"
license = "MIT/Apache-2.0"
keywords = ["Kerberos","parser","nom"]
homepage = "https://github.com/rusticata/kerberos-parser"
repository = "https://github.com/rusticata/kerberos-parser.git"
name = "kerberos-parser"
version = "0.3.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
categories = ["parser-implementations"]
readme = "README.md"

include = [
  "LICENSE-*",
  "README.md",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "assets/*.bin",
  "benches/*.rs",
  "src/*.rs",
  "tests/*.rs"
]

[dependencies]
nom = "4.2"
rusticata-macros = "1.0"
der-parser = "2.0.0-alpha1"

[badges]
travis-ci = { repository = "rusticata/kerberos-parser" }
